name: shell commands

on:
  - push

jobs:
  run-shell-command:
    runs-on: ubuntu-18.04
    steps:
      - name: echo string
        run: echo "Hello World"
      - name: Multi line script
        run: |
          node -v
          npm -v
      - name: run command
        run: ls -a